### ISSUE TITLE
does it work for tx1 R24.1 Ubuntu 14.04 ?

### ISSUE THREAD

**Issue by inckagan** [jetsonhacks/installCaffeJTX1#6]
Hi, I am a newbie to the hardware and trying to install caffe on my TX1. Does this sh work for R24.1 as well ? Thanks in advance

**Comment by jetsonhacks** [comment]
No. This release uses cuDNN 6.0 which support versions of Tensorflow > 0.12.

**Comment by jetsonhacks** [comment]
Oops, wrong project comment.

**Comment by jetsonhacks** [comment]
It has not been tested against L4T 24.1.

**Comment by inckagan** [comment]
Sorry I did not understand. I was asking if this project works for R24.1 as well or not ?

**Comment by inckagan** [comment]
Thank you for the reply. Could you please guide me which steps might be different while installing for R24.1 ?

**Comment by jetsonhacks** [comment]
The changes in OS and different support libraries probably means that you will probably need to make changes to the scripts for it to work.

**Comment by jetsonhacks** [comment]
You can look at the tagged version 1.0 for something that might be closer to working for that configuration. Caffe is a fast moving project, and some of the work arounds from back then need to be updated.
